apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-cloud-projects-site
  namespace: learn-master
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aws-cloud-projects-site
  template:
    metadata:
      labels:
        app: aws-cloud-projects-site
    spec:
      containers:
      - name: aws-cloud-projects-site
        image: mllsatyanarayana/aws-cloud-projects-site:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
