name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: satya-k8-poc
  REGION: us-central1
  REPOSITORY: satya-gcr
  IMAGE_NAME: aws-cloud-projects-site

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Use service account key authentication
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}
            # Replace the following placeholders with your actual Workload Identity Provider
            workload_identity_provider: 'projects/313075394932/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
            service_account: 'github-actions@satya-k8-poc.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build and Push Docker image
        run: |
          IMAGE_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          IMAGE_LATEST="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:lates